### ISSUE TITLE
Crashes in my modpack on linux debian 12

### ISSUE THREAD

**Issue by Mysticpasta1** [Jkaano/Too-Many-Keybinds#18]
[crash-2024-11-27_09.48.14-fml.txt](https://github.com/user-attachments/files/17932355/crash-2024-11-27_09.48.14-fml.txt)

**Comment by Jkaano** [comment]
Crash caused by Java robot, will investigate later. Currently taking time to actually learn Java in hopes to improve code, sorry for the inconvenience.

**Comment by Jkaano** [comment]
Potential resolve for this is having the mod try to use the robot and if it can't just switch to the alternative method of key presses without the robot, instead of calling a crash.
